version: '3.8'
services:
  pessoa_service:
    build: ./pessoa_service
    ports:
      - "8081:8081"
  atividade_service:
    build: ./atividade_service
    ports:
      - "8080:8080"
    depends_on:
      - pessoa_service