version: "3.8"

services:
  atividade:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    networks:
      - projeto-apis

networks:
  projeto-apis:
    external: true